In [1]:
# Standard imports
# %matplotlib inline # No longer required in newer versions of Jupyter (2022+)
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import sklearn
print(f"Using Scikit-Learn version: {sklearn.__version__} (materials in this notebook require this version or newer).")

Using Scikit-Learn version: 1.9.0 (materials in this notebook require this version or newer).

Get ready

Random Forest Classifier Workflow for Classifying Heart Disease

In [2]:
import pandas as pd

# heart_disease = pd.read_csv("../data/heart-disease.csv") # load data from local directory
heart_disease = pd.read_csv("/Users/shahjalalmd/Desktop/Scikit-learn/heart.csv") # load data directly from URL (requires raw form on GitHub, source: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/heart-disease.csv)
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [3]:
# Create X (all the feature columns)
X = heart_disease.drop("target", axis=1)

# Create y (the target column)
y = heart_disease["target"]

# Check the head of the features DataFrame
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2

In [4]:
# Check the head and the value counts of the labels 
y.head(), y.value_counts()

(0    0
 1    0
 2    0
 3    0
 4    0
 Name: target, dtype: int64,
 target
 1    526
 0    499
 Name: count, dtype: int64)

In [5]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y,
                                                    test_size=0.25) # by default train_test_split uses 25% of the data for the test set

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((768, 13), (257, 13), (768,), (257,))

2. Choose the model and hyperparameters

In [6]:
# Since we're working on a classification problem, we'll start with a RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

In [7]:
# View the current hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

3. Fit the model to the data and use it to make a prediction

In [8]:
clf.fit(X=X_train, y=y_train)

RandomForestClassifier()

Use the model to make a prediction

In [10]:
# This doesn't work... incorrect shapes
y_label = clf.predict(np.array([[0, 2, 3, 4]]))

/Users/shahjalalmd/Research/m-healthresearch/.venv/lib/python3.11/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: X has 4 features, but RandomForestClassifier is expecting 13 features as input.

We get a ValueError (mismatched shapes):

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
This happens because we're trying to make predictions on data that is in a different format to the data our model was trained on.

Since our model was trained on data from X_train, predictions should be made on data in the same format and shape as X_train.

Our goal in many machine learning problems is to use patterns learned from the training data to make predictions on the test data (or future unseen data).

In [11]:
# In order to predict a label, data has to be in the same shape as X_train
X_test.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
834,42,1,0,136,315,0,1,125,1,1.8,1,0,1
847,61,1,0,138,166,0,0,125,1,3.6,1,1,2
327,57,1,0,150,276,0,0,112,1,0.6,1,1,1
526,62,0,0,160,164,0,0,145,0,6.2,0,3,3
982,67,0,0,106,223,0,1,142,0,0.3,2,2,2

In [12]:
# Use the model to make a prediction on the test data (further evaluation)
y_preds = clf.predict(X=X_test)

4. Evaluate the model

In [13]:
# Evaluate the model on the training set
train_acc = clf.score(X=X_train, y=y_train)
print(f"The model's accuracy on the training dataset is: {train_acc*100}%")

The model's accuracy on the training dataset is: 100.0%

In [14]:
# Evaluate the model on the test set
test_acc = clf.score(X=X_test, y=y_test)
print(f"The model's accuracy on the testing dataset is: {test_acc*100:.2f}%")

The model's accuracy on the testing dataset is: 98.83%

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Create a classification report
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99       117
           1       0.98      1.00      0.99       140

    accuracy                           0.99       257
   macro avg       0.99      0.99      0.99       257
weighted avg       0.99      0.99      0.99       257

In [16]:
# Create a confusion matrix
conf_mat = confusion_matrix(y_test, y_preds)
conf_mat

array([[114,   3],
       [  0, 140]])

In [17]:
# Compute the accuracy score (same as the score() method for classifiers) 
accuracy_score(y_test, y_preds)

0.9883268482490273

5. Experiment to improve

In [18]:
# Try different numbers of estimators (trees)... (no cross-validation)
np.random.seed(42)
for i in range(100, 200, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 100 estimators...
Model accuracy on test set: 98.83%

Trying model with 110 estimators...
Model accuracy on test set: 98.83%

Trying model with 120 estimators...
Model accuracy on test set: 98.83%

Trying model with 130 estimators...
Model accuracy on test set: 97.67%

Trying model with 140 estimators...
Model accuracy on test set: 98.83%

Trying model with 150 estimators...
Model accuracy on test set: 98.83%

Trying model with 160 estimators...
Model accuracy on test set: 98.83%

Trying model with 170 estimators...
Model accuracy on test set: 98.83%

Trying model with 180 estimators...
Model accuracy on test set: 98.83%

Trying model with 190 estimators...
Model accuracy on test set: 98.83%

In [ ]:
from sklearn.model_selection import cross_val_score

# With cross-validation
np.random.seed(42)
for i in range(100, 200, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)

    # Measure the model score on a single train/test split
    model_score = model.score(X_test, y_test)
    print(f"Model accuracy on single test set split: {model_score * 100:.2f}%")
    
    # Measure the mean cross-validation score across 5 different train and test splits
    cross_val_mean = np.mean(cross_val_score(model, X, y, cv=5))
    print(f"5-fold cross-validation score: {cross_val_mean * 100:.2f}%")
    
    print("")

Trying model with 100 estimators...
Model accuracy on single test set split: 98.83%
5-fold cross-validation score: 99.71%

Trying model with 110 estimators...
Model accuracy on single test set split: 98.83%
5-fold cross-validation score: 99.71%

Trying model with 120 estimators...
Model accuracy on single test set split: 98.83%
5-fold cross-validation score: 99.71%

Trying model with 130 estimators...
Model accuracy on single test set split: 97.67%
5-fold cross-validation score: 99.41%

Trying model with 140 estimators...
Model accuracy on single test set split: 98.83%
5-fold cross-validation score: 99.71%

Trying model with 150 estimators...
Model accuracy on single test set split: 97.67%
5-fold cross-validation score: 99.71%

Trying model with 160 estimators...
Model accuracy on single test set split: 98.83%
5-fold cross-validation score: 99.71%

Trying model with 170 estimators...
Model accuracy on single test set split: 98.83%
5-fold cross-validation score: 99.71%

Trying model with 180 estimators...
Model accuracy on single test set split: 98.83%
5-fold cross-validation score: 99.71%

Trying model with 190 estimators...
Model accuracy on single test set split: 98.83%

In [ ]:
# Another way to do it with GridSearchCV...
np.random.seed(42)
from sklearn.model_selection import GridSearchCV

# Define the parameters to search over in dictionary form 
# (these can be any of your target model's hyperparameters) 
param_grid = {'n_estimators': [i for i in range(100, 200, 10)]}

# Setup the grid search
grid = GridSearchCV(estimator=RandomForestClassifier(),
                    param_grid=param_grid,
                    cv=5,
                    verbose=1) 

# Fit the grid search to the data
grid.fit(X, y)

# Find the best parameters
print(f"The best parameter values are: {grid.best_params_}")
print(f"With a score of: {grid.best_score_*100:.2f}%")